trigger: none

pool:
  vmImage: 'ubuntu-latest'

variables:
  azureServiceConnection: 'AzureServiceConnection'  # This is the Azure service connection you set up in Azure DevOps
  terraformVersion: '1.5.0'  # Change to your desired Terraform version

steps:
  - task: TerraformInstaller@1
    displayName: install
    inputs:
      terraformVersion: 'latest'
