trigger: none

pool:
  vmImage: 'ubuntu-latest'

variables:
  azureServiceConnection: 'AzureServiceConnection'  # This is the Azure service connection you set up in Azure DevOps
  terraformVersion: '1.5.0'  # Change to your desired Terraform version

steps:
  - task: UseTerraform@0
    inputs:
      terraformVersion: $(terraformVersion)

  - task: AzureCLI@2
    displayName: 'Azure CLI - Terraform Init'
    inputs:
      azureSubscription: $(azureServiceConnection)  # Azure service principal connection
      scriptType: 'bash'
      scriptLocation: 'inlineScript'
      inlineScript: |
        terraform init

  - task: AzureCLI@2
    displayName: 'Azure CLI - Terraform Plan'
    inputs:
      azureSubscription: $(azureServiceConnection)
      scriptType: 'bash'
      scriptLocation: 'inlineScript'
      inlineScript: |
        terraform plan

  - task: AzureCLI@2
    displayName: 'Azure CLI - Terraform Apply'
    inputs:
      azureSubscription: $(azureServiceConnection)
      scriptType: 'bash'
      scriptLocation: 'inlineScript'
      inlineScript: |
        terraform apply -auto-approve
