trigger:
  - none

pool:
  vmImage: 'ubuntu-latest'  # The agent to run the pipeline on

variables:
  TF_VERSION: '1.5.0'  # Set the version of Terraform you want to use
  TF_WORKSPACE: 'default'  # Set the workspace, default is usually fine
  ARM_CLIENT_ID: $(azureServicePrincipal.clientId)  # Azure Service Principal details
  ARM_CLIENT_SECRET: $(azureServicePrincipal.clientSecret)
  ARM_SUBSCRIPTION_ID: $(azureServicePrincipal.subscriptionId)
  ARM_TENANT_ID: $(azureServicePrincipal.tenantId)

stages:
  - stage: Terraform
    jobs:
      - job: TerraformJob
        steps:

          # Step 1: Install Terraform manually
          - script: |
              echo "Installing Terraform..."
              c
            displayName: 'Install Terraform'
